/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.67
 * Generated at: 2018-12-27 03:49:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class thread_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("        \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>水滴工作室</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\tbody{ \r\n");
      out.write("\t\tmargin: 0px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#box{\r\n");
      out.write("\t\twidth:1700px;\r\n");
      out.write("\t\theight:2000px;\r\n");
      out.write("\t\tborder:auto; \r\n");
      out.write("\t}\r\n");
      out.write("\ta{text-decoration:none; }\r\n");
      out.write("\t\t.shuidi{\r\n");
      out.write("\t\t\twidth:1200px;\r\n");
      out.write("\t\t\theight:50px;\r\n");
      out.write("\t\t\tmargin-top: 23px; \r\n");
      out.write("\t\t\tborder:auto ; \r\n");
      out.write("\t\t\tfloat: left;\r\n");
      out.write("\t\t\tmargin-left:250px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.font_01\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tfont-size:32px;\r\n");
      out.write("\t\t\tfont-style: black;\r\n");
      out.write("\t\t} \r\n");
      out.write("\t\t.logo{margin-left: 20px;margin-top: 10px;  }\r\n");
      out.write("\t\t.login{float: right;\r\n");
      out.write("\t\t\tfont-size:28px;\r\n");
      out.write("\t\t\tmargin-top:10px;\r\n");
      out.write("\t\t\tmargin-right: 40px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t    #box1{ width: 400px;    \r\n");
      out.write("\t\t       margin: 55px auto;         \r\n");
      out.write("\t\t       font-size: 14px;    } \r\n");
      out.write("\t\t  input{width: 260px;     \r\n");
      out.write("\t\t       border: 1px solid #e2e2e2;      \r\n");
      out.write("\t\t       height: 30px;                 \r\n");
      out.write("\t\t        background-repeat: no-repeat;  \r\n");
      out.write("\t\t        padding:0 0 0 40px;    }  \r\n");
      out.write("\t\t    #search{ width: 78px;\r\n");
      out.write("\t\t    \theight: 32px;\r\n");
      out.write("\t\t    \tfloat: right;\r\n");
      out.write("\t\t    \tbackground: black;\r\n");
      out.write("\t\t    \tcolor: white; \r\n");
      out.write("\t\t    \t text-align: center;\r\n");
      out.write("\t\t    \t line-height: 32px; \r\n");
      out.write("\t\t    \t cursor: pointer;    } \r\n");
      out.write("\t\t    .border{\r\n");
      out.write("\t\t    \twidth: 1200px;\r\n");
      out.write("\t\t\t\theight:800px;\r\n");
      out.write("\t\t\t\tborder: 3px solid black;  \r\n");
      out.write("\t\t\t \tborder-radius:10px 10px 10px 10px;\r\n");
      out.write("\t\t\t\tmargin: auto;}\r\n");
      out.write("\t\t\t#box2{\r\n");
      out.write("\t\t\t\twidth:800px;\r\n");
      out.write("\t\t\t\theight:750px;\r\n");
      out.write("\t\t\t\tmargin-top:5px;\r\n");
      out.write("\t\t\t\tfloat:left;\r\n");
      out.write("\t\t\t\tmargin-left:2px;\r\n");
      out.write("\t\t\t\tborder:1px solid black;\r\n");
      out.write("\t\t\t\tborder-radius:5px 5px 5px 5px;\r\n");
      out.write("\t\t\t\tposition:absolute; \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t#box3{\r\n");
      out.write("\t\t\t\t\twidth:750px;\r\n");
      out.write("\t\t\t\t\theight:700px;\r\n");
      out.write("\t\t\t\t\tmargin-top:40px;\r\n");
      out.write("\t\t\t\t\tfloat:left;\r\n");
      out.write("\t\t\t\t\tmargin-left: 30px; \r\n");
      out.write("\t\t\t\t\tborder:1px solid black;\r\n");
      out.write("\t\t\t\t\tborder-radius:5px 5px 5px 5px;\r\n");
      out.write("\t\t\t\t\tposition:absolute;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t#box4{\r\n");
      out.write("\t\t\t\t\twidth:280px;\r\n");
      out.write("\t\t\t\t\theight:700px;\r\n");
      out.write("\t\t\t\t\tmargin-top:4px;\r\n");
      out.write("\t\t\t\t\tfloat:left;\r\n");
      out.write("\t\t\t\t\tmargin-left:1000px;\r\n");
      out.write("\t\t\t\t\tborder:1px solid black;\r\n");
      out.write("\t\t\t\t\tborder-radius:5px 5px 5px 5px;\r\n");
      out.write("\t\t\t\t\tposition:absolute;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t.style01{\r\n");
      out.write("\t\t\t\twidth:200px;\r\n");
      out.write("\t\t\t\theight:50px;\r\n");
      out.write("\t\t\t\tfloat:left;\r\n");
      out.write("\t\t\t\tmargin-left:30px;\r\n");
      out.write("\t\t\t\tmargin-top:7px;\r\n");
      out.write("\t\t\t\tfont-size:20px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.style02{\r\n");
      out.write("\t\t\t\twidth:200px;\r\n");
      out.write("\t\t\t\theight:50px;\r\n");
      out.write("\t\t\t\tfloat:left;\r\n");
      out.write("\t\t\t\tmargin-left:35px;\r\n");
      out.write("\t\t\t\tmargin-top:7px;\r\n");
      out.write("\t\t\t\tfont-size:20px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.style03{\r\n");
      out.write("\t\t\t\twidth:200px;\r\n");
      out.write("\t\t\t\theight:50px;\r\n");
      out.write("\t\t\t\tfloat:left;\r\n");
      out.write("\t\t\t\tmargin-left:40px;\r\n");
      out.write("\t\t\t\tmargin-top:7px;\r\n");
      out.write("\t\t\t\tfont-size:20px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.class01{\r\n");
      out.write("\t\t\t\twidth:200px;\r\n");
      out.write("\t\t\t\theight:50px;\r\n");
      out.write("\t\t\t\tfloat:left;\r\n");
      out.write("\t\t\t\tmargin-left: 90px;\r\n");
      out.write("\t\t\t\tmargin-top: 7px; \r\n");
      out.write("\t\t\t\tfont-size:30px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.calss02{\r\n");
      out.write("\t\t\t\twidth:200px;\r\n");
      out.write("\t\t\t\theight:50px;\r\n");
      out.write("\t\t\t\tfloat:left;\r\n");
      out.write("\t\t\t\tmargin-left: 180px;\r\n");
      out.write("\t\t\t\tmargin-top: 7px;\r\n");
      out.write("\t\t\t\tfont-size:30px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.calss03{\r\n");
      out.write("\t\t\t\twidth:200px;\r\n");
      out.write("\t\t\t\theight:50px;\r\n");
      out.write("\t\t\t\tfloat:left;\r\n");
      out.write("\t\t\t\tmargin-left: 270px;\r\n");
      out.write("\t\t\t\tmargin-top: 7px;\r\n");
      out.write("\t\t\t\tfont-size:30px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.class04{\r\n");
      out.write("\t\t\t\twidth:200px;\r\n");
      out.write("\t\t\t\theight:50px;\r\n");
      out.write("\t\t\t\tfloat:left;\r\n");
      out.write("\t\t\t\tmargin-left:360px;\r\n");
      out.write("\t\t\t\tmargin-top: 7px;\r\n");
      out.write("\t\t\t\tfont-size:30px;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.class05{\r\n");
      out.write("\t\t\t\twidth:100px;\r\n");
      out.write("\t\t\t\theight: 50px;\r\n");
      out.write("\t\t\t\tfloat: left;\r\n");
      out.write("\t\t\t\tmargin-left: 80px;\r\n");
      out.write("\t\t\t\tmargin-top: 700px;\r\n");
      out.write("\t\t\t\tfont-size:20px;\r\n");
      out.write("\t\t\t}\t\r\n");
      out.write("\t\t\t*{margin:0px; padding: 0px; }\r\n");
      out.write("\t\t#dh{\r\n");
      out.write("\t\t\tposition: relative;\r\n");
      out.write("\t\t\tmargin-top: 0px;\r\n");
      out.write("\t\t\twidth: 1600px;\r\n");
      out.write("\t\t\theight:40px;\r\n");
      out.write("\t\t\tborder: 0px;\r\n");
      out.write("\t\t\tfont-size:20px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#dh ul{\r\n");
      out.write("\t\t\tpadding: 0px;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\ta{\r\n");
      out.write("\t\t\tcolor: black;\r\n");
      out.write("\t\t\twidth: 100px;\r\n");
      out.write("\t\t\theight: 40px;\r\n");
      out.write("\t\t\tdisplay: block;\r\n");
      out.write("\t\t\ttext-decoration: none;\r\n");
      out.write("\t\t\ttext-align: center;\r\n");
      out.write("\t\t\tline-height: 40px;\r\n");
      out.write("\t\t\tfont-family: Microsoft Yahei;\r\n");
      out.write("\t\t\tfont-weight: 2px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#dh {\r\n");
      out.write("\t\t\tmargin:0px auto; \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#dh ul li {\r\n");
      out.write("\t\t\tlist-style: none;\r\n");
      out.write("\t\t\tfloat: left;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#dh ul li a:hover{\r\n");
      out.write("\t\t\tbackground-color: #6699FF;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#dh ul:hover{\r\n");
      out.write("\t\t\tdisplay: block;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#dh ul li ul{\r\n");
      out.write("\t\t\tbackground-color: #0099CC;\r\n");
      out.write("\t\t\tposition: absolute;\r\n");
      out.write("\t\t\tdisplay: none;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#dh ul li ul li{\r\n");
      out.write("\t\t\tfloat: none;\r\n");
      out.write("\t\t\tbackground-color: #6688EE;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#dh ul li ul li a{\r\n");
      out.write("\t\t\tfont-size: 13px;\r\n");
      out.write("\t\t\tfont-weight: 0px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#dh ul li:hover ul{            \r\n");
      out.write("\t\t\tdisplay: block;\r\n");
      out.write("\t\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"box\"> \r\n");
      out.write("<div>\r\n");
      out.write("\t    <div class=\"logo\" >\r\n");
      out.write("\t\t\t<img src=\"img/shuidi .png\" width=\"360\" height=\"130\">\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t<div class=\"shuidi\" \">\r\n");
      out.write("\t\t<div id=\"dh\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/second.jsp?name=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${one_category.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${one_category.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(":课程</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/second.jsp?name=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${one_category.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${one_category.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(":章节</a></li>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t             <li><a href=\"#\">第一章</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">第二章</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">第三章</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t<li><a href=\"#\">小节</a>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">1.1</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">1.2</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">1.3</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t<div id=\"box2\">\r\n");
      out.write("\t\t<div class=\"style01\" color:yellow;>视频名称：</div>\r\n");
      out.write("\t\t<div class=\"style02\">发布作者：</div>\r\n");
      out.write("\t\t<div class=\"style03\">点击次数：</div>\r\n");
      out.write("\t\t<div id=\"box3\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"box4\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"class05\">发表</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t<div id=\"box1\">\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body> \r\n");
      out.write("</html> \r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
